Django/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from Django import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^googly/',include('googly.urls',namespace='googly')),
    url(r'^twitty/',include('twitty.urls',namespace='twitty')),
    url(r'^gitty/',include('gitty.urls',namespace='gitty')),
    url(r'^api/',include('api.urls',namespace='api')),
    url(r'^accounts/',include('allauth.urls')),

]
# 3ashan ata3araf el el two files (Media & Static)
if settings.DEBUG:
	urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import url
from . import views 

urlpatterns = [
    url(r'^login/$', views.UserLoginView.as_view(), name="login"),

    url(r'^$',views.PostListView.as_view(), name="list"),
    url(r'^create/$', views.PostCreateView.as_view(), name ="create"),
    url(r'^(?P<post_slug>[-\w]+)/$', views.PostDetailView.as_view(), name="detail"),
    url(r'^(?P<post_slug>[-\w]+)/delete/$', views.PostDeleteView.as_view(), name="delete"),
    url(r'^(?P<post_slug>[-\w]+)/update/$', views.PostUpdateView.as_view(), name="update"),
    url(r'^register/$', views.UserCreateView.as_view(), name="register"),


]

googly/urls.py
from django.conf.urls import url
from .import views 

urlpatterns = [
	url(r'^place/search/$',views.place_text_search, name ="place-search"),
	url(r'^place/detail/$',views.place_detail, name ="place-detail"),

]

googly/models.py
from django.db import models

# Create your models here.

googly/views.py
from django.http import JsonResponse
from django.shortcuts import render
import requests

def place_text_search(request):
	key = "AIzaSyAh8mNvElk9-Ad7oP7eJUbTzydc1IC98NA"
	query = request.GET.get('query', 'coded')
	url = "https://maps.googleapis.com/maps/api/place/textsearch/json?query=%s&region=kw&key=%s"%(query, key)

	next_page = request.GET.get('nextpage')
	if next_page is not None:
		url += "&pagetoken="+next_page

	response = requests.get(url)

	context = {
	"response": response.json()
	}
	return render(request, 'place_search.html', context)
	# return JsonResponse( response.json(), safe=False)

def place_detail(request):
	key = "AIzaSyAh8mNvElk9-Ad7oP7eJUbTzydc1IC98NA"	
	place_id = request.GET.get('place_id','')
	url = "https://maps.googleapis.com/maps/api/place/details/json?key=%s&placeid=%s"%(key, place_id)
	map_key ="AIzaSyDaqs7XUSY5-alChNWRcuwlcALkLgT2Kpc"

	response = requests.get(url)
	context = {
	"response": response.json(),
	"map":map_key,
	}
	return render (request, 'place_detail.html', context)
	#return JsonResponse( response.json(), safe=False)



		

googly/templates/baseg.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>
		{% block title %} 
		{% endblock title %}
	</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
	


    <div class="container">

	{% block content %}
	{% endblock content %}
	
	</div>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

googly/templates/place_detail.html
{% extends "baseg.html" %}

{% block content %}
<div class="card">
  <h4 class="card-header">{{response.result.vicinity}}</h4>
  <div class="card-body">
    <h4 class="card-title">{{response.result.name}}</h4>
    <p class="card-text">Address: {{response.result.formatted_address}}</p>
    <a href="{{response.result.url}}" class="btn btn-danger"><i class="fa fa-bicycle" aria-hidden="true"></i></a>
  </div>
</div>



<iframe
  id = "map"
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="" allowfullscreen>
</iframe>

<script>
	
	function do_something(lat,lng){
		var map = $("#map");
		map.attr(
			'src',
			"https://www.google.com/maps/embed/v1/directions?key={{map}}&origin="+lat+","+lng+"&destination={{response.result.geometry.location.lat}},{{response.result.geometry.location.lng}}"

			)
	}


	navigator.geolocation.getCurrentPosition(function(position) {
  do_something(position.coords.latitude, position.coords.longitude);
});
</script>

{% endblock content %}

googly/templates/place_search.html
{% extends "baseg.html" %}

{% block content %}
<form action="{% url 'googly:place-search' %}" method="GET">
  <div class="col-lg-6">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search for..." aria-label="Search for..." name="query">
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="submit">Search</button>
      </span>
    </div>
  </div>
</form>
<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Detail</th>
    </tr>
  </thead>
  <tbody>
  	{% for place in response.results %}
    <tr>
      <td>{{place.name}}</td>
      <td>{{place.formatted_address}}</td>
      <td>
      	<form action="{% url 'googly:place-detail' %}" method="GET">
      		<input type="hidden" name="place_id" value='{{place.place_id}}'>
    		<input type="submit" value="Detail" class="btn btn-outline-info">
      	</form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if response.next_page_token %}
    <form action="{% url 'googly:place-search' %}" method="GET">
    	<input type="hidden" name="nextpage" value='{{response.next_page_token}}'>
    	<input type="submit" value="More Results..." class="btn btn-outline-info">
    </form>	
{% endif %}
{% endblock content %}